version: '3.7'
services:

  backend:
    image: docker.pkg.github.com/scoreboard-tcc/backendnovo/backend:latest
    restart: never
    environment:
      - APP_PORT=8080
      - BROKER_WS_PORT=8081
      - BROKER_STANDALONE_PORT=1883
      - POSTGRES_URL=postgresql://postgres:1234@localhost:5432/scoreboard?schema=public
      - MONGO_URL=mongodb://mongo:1234@localhost:27017/scoreboard?authSource=admin
      - JWT_SECRET=ahdfkljsahdflksdh
      - FIREBASE_DATABASE_URL=https://scoreboard-31923.firebaseio.com
      - FIREBASE_STORAGE_BUCKET=scoreboard-31923.appspot.com
      - FIREBASE_UPLOAD_PATH=https://storage.googleapis.com/scoreboard-31923.appspot.com/
      - GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json
      - BROKER_PERSISTENCE_URL=mongodb://mongo:1234@localhost:27017/broker?authSource=admin
    ports:
      - 1883:1883
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
      - mongo


  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=scoreboard
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  test_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=scoreboard
    ports:
      - 5433:5432

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=scoreboard
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  test_mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
  
volumes:
  pgdata:
  mongodata: