name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.18.2
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.2'
    - name: Install yarn
      run: |
        yarn
      env:
        CI: true
    - name: Creates serviceAccountKey.json
      run: |
        touch tmp.txt
        echo ${{ secrets.FIREBASE_CONFIG }} >> tmp.txt
        openssl enc -base64 -A -d -in tmp.txt -out serviceAccountKey.json
        rm tmp.txt
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      with:
        name: scoreboard-tcc/backendnovo/backend
        registry: docker.pkg.github.com
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: latest
        buildargs: POSTGRES_URL
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
        IMAGE: backend
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        MONGO_URL: ${{ secrets.MONGO_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_UPLOAD_PATH: ${{ secrets.FIREBASE_UPLOAD_PATH }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        BROKER_PERSISTENCE_URL: ${{ secrets.BROKER_PERSISTENCE_URL }}
        BROKER_STANDALONE_PORT: ${{ secrets.BROKER_STANDALONE_PORT }}
        BROKER_WS_PORT: ${{ secrets.BROKER_WS_PORT }}
        APP_PORT: ${{ secrets.APP_PORT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: IMAGE, GH_USERNAME, GITHUB_TOKEN, POSTGRES_URL, MONGO_URL, JWT_SECRET, FIREBASE_DATABASE_URL, FIREBASE_STORAGE_BUCKET, FIREBASE_UPLOAD_PATH, GOOGLE_APPLICATION_CREDENTIALS, BROKER_PERSISTENCE_URL, BROKER_STANDALONE_PORT,BROKER_WS_PORT, APP_PORT
        script: |
          docker login docker.pkg.github.com -u $GH_USERNAME -p $GITHUB_TOKEN
          POSTGRES_URL=$POSTGRES_URL MONGO_URL=$MONGO_URL JWT_SECRET=$JWT_SECRET FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET FIREBASE_UPLOAD_PATH=$FIREBASE_UPLOAD_PATH GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS BROKER_PERSISTENCE_URL=$BROKER_PERSISTENCE_URL BROKER_STANDALONE_PORT=$BROKER_STANDALONE_PORT BROKER_WS_PORT=$BROKER_WS_PORT APP_PORT=$APP_PORT docker-compose stop $IMAGE || true
          POSTGRES_URL=$POSTGRES_URL MONGO_URL=$MONGO_URL JWT_SECRET=$JWT_SECRET FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET FIREBASE_UPLOAD_PATH=$FIREBASE_UPLOAD_PATH GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS BROKER_PERSISTENCE_URL=$BROKER_PERSISTENCE_URL BROKER_STANDALONE_PORT=$BROKER_STANDALONE_PORT BROKER_WS_PORT=$BROKER_WS_PORT APP_PORT=$APP_PORT docker-compose up --force-recreate --build -d $IMAGE