name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.18.2
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.2'
    - name: Install yarn and run unittest
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: scoreboard-tcc/backendnovo/backend
        registry: docker.pkg.github.com
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: latest
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
        IMAGE: backend
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        MONGO_URL: ${{ secrets.MONGO_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: IMAGE, GH_USERNAME, GITHUB_TOKEN, POSTGRES_URL, MONGO_URL, JWT_SECRET
        script: |
          docker stop $IMAGE || true
          docker login docker.pkg.github.com -u $GH_USERNAME -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/scoreboard-tcc/backendnovo/$IMAGE:latest
          docker run -dit -p 8080:8080 -p 8081:8081 -e POSTGRES_URL=$POSTGRES_URL -e MONGO_URL=$MONGO_URL -e JWT_SECRET=$JWT_SECRET docker.pkg.github.com/scoreboard-tcc/backendnovo/$IMAGE:latest